# Generated by Django 5.1.7 on 2025-03-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('owner', 'Owner'), ('finance', 'Finance'), ('warehouse', 'Warehouse')], max_length=50, unique=True),
        ),
    ]
