# Generated by Django 5.1.7 on 2025-06-15 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_customer_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='document_type',
            field=models.CharField(choices=[('PO', 'Purchase Order'), ('SO', 'Sales Order'), ('DO', 'Delivery Order'), ('GRN', 'Goods Received Note')], max_length=10),
        ),
    ]
