# Generated by Django 5.1.7 on 2025-07-02 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_supplier_email_alter_transaction_document_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SJ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('vehicle_number', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.customer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SJItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carton_quantity', models.IntegerField(default=0)),
                ('pack_quantity', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
                ('sj', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.sj')),
            ],
        ),
        migrations.CreateModel(
            name='SPG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(blank=True, max_length=100)),
                ('document_type', models.CharField(choices=[('IMPORT', 'Import'), ('BAWANG', 'Bawang'), ('KAWAT', 'Kawat'), ('LAIN-LAIN', 'Lain-lain')], max_length=10)),
                ('container_number', models.CharField(max_length=50)),
                ('vehicle_number', models.CharField(max_length=50)),
                ('sj_number', models.CharField(max_length=100)),
                ('start_unload', models.CharField(max_length=50)),
                ('finish_load', models.CharField(max_length=50)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SPGItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carton_quantity', models.IntegerField(default=0)),
                ('pack_quantity', models.IntegerField(default=0)),
                ('packaging_size', models.CharField(max_length=50)),
                ('inn', models.CharField(max_length=10)),
                ('out', models.CharField(max_length=10)),
                ('pjg', models.CharField(max_length=10)),
                ('warehouse_size', models.CharField(max_length=50)),
                ('packaging_weight', models.CharField(max_length=10)),
                ('warehouse_weight', models.CharField(max_length=10)),
                ('production_code', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
                ('spg', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.spg')),
            ],
        ),
        migrations.CreateModel(
            name='SPK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.customer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='sj',
            name='spk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.spk'),
        ),
        migrations.CreateModel(
            name='SPKItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carton_quantity', models.IntegerField(default=0)),
                ('pack_quantity', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
                ('sj', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.spk')),
            ],
        ),
        migrations.CreateModel(
            name='SuratLain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(max_length=100)),
                ('document_type', models.CharField(choices=[('STB', 'STB'), ('SPB', 'SPB'), ('RETUR_PEMBELIAN', 'Retur Pembelian')], max_length=100)),
                ('sj_number', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.warehouse')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SuratLainItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carton_quantity', models.IntegerField(default=0)),
                ('pack_quantity', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
                ('surat_lain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.suratlain')),
            ],
        ),
        migrations.CreateModel(
            name='SuratTransferStok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destination_transfers', to='inventory.warehouse')),
                ('source_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_transfers', to='inventory.warehouse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SuratTransferStokItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carton_quantity', models.IntegerField(default=0)),
                ('pack_quantity', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
                ('surat_transfer_stok', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.surattransferstok')),
            ],
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
