# Generated by Django 5.1.7 on 2025-07-02 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_sj_sjitems_spg_spgitems_spk_sj_spk_spkitems_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spgitems',
            name='spg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory.spg'),
        ),
    ]
