# Generated by Django 5.1.7 on 2025-07-05 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_spgitems_spg'),
    ]

    operations = [
        migrations.AddField(
            model_name='spg',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spg',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
