# Generated by Django 5.1.7 on 2025-07-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_surattransferstok_deleted_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spkitems',
            old_name='sj',
            new_name='spk',
        ),
        migrations.AddField(
            model_name='spk',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spk',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
