# Generated by Django 5.1.7 on 2025-07-05 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_rename_sj_spkitems_spk_spk_deleted_at_spk_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spkitems',
            name='spk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory.spk'),
        ),
    ]
