# Generated by Django 5.1.7 on 2025-07-11 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_spkitems_spk'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='upline',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='spg',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
