# Generated by Django 5.1.7 on 2025-07-12 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_product_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sj',
            name='transaction_date',
        ),
        migrations.AddField(
            model_name='sj',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sj',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sj',
            name='document_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sjitems',
            name='sj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory.sj'),
        ),
        migrations.AlterField(
            model_name='suratlain',
            name='document_type',
            field=models.CharField(choices=[('STB', 'STB'), ('SPB', 'SPB'), ('RETUR_PEMBELIAN', 'Retur Pembelian'), ('RETUR_PENJUALAN', 'Retur Penjualan')], max_length=100),
        ),
    ]
