# Generated by Django 5.1.7 on 2025-07-12 16:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_remove_sj_transaction_date_sj_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sj',
            name='transaction_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
