# Generated by Django 5.1.7 on 2025-07-21 06:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_suratlain_deleted_at_suratlain_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spg',
            name='transaction_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
