# Generated by Django 5.1.7 on 2025-07-26 17:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_surattransferstok_transaction_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suratlain',
            name='transaction_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
