# Generated by Django 5.1.7 on 2025-08-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_remove_spk_warehouse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sj',
            name='is_customer',
        ),
        migrations.AddField(
            model_name='sj',
            name='sj_type',
            field=models.CharField(choices=[('KA', 'KA'), ('KA-SJ', 'KA-SJ'), ('SO/B', 'SO/B'), ('SO/K', 'SO/K'), ('P-B', 'P-B'), ('P-K', 'P-K')], default='KA', max_length=10),
            preserve_default=False,
        ),
    ]
