# Generated by Django 5.1.7 on 2025-08-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_remove_sj_is_customer_sj_sj_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sj',
            name='sequence_number',
            field=models.PositiveIntegerField(db_index=True, editable=False, null=True),
        ),
    ]
