# Generated by Django 5.1.7 on 2025-08-12 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_stockadjustment_stockadjustmentitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockadjustment',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='stockadjustment',
            name='is_deleted',
        ),
    ]
