# Generated by Django 5.1.7 on 2026-06-18 07:27

from django.db import migrations, models


def set_category_sort_order(apps, schema_editor):
    Category = apps.get_model('inventory', 'Category')
    sort_order_map = {
        'ROMAN CANDLE': 1,
        'SMALL ITEMS': 2,
        'CAKE': 3,
        'BAWANG': 4,
        'KAWAT': 5,
        'LOKAL': 6,
        'CAKE DISPLAY': 7,
        'SINGLE ROW': 8,
        'SINGLE SHOT': 9,
        'DAY FIREWORKS CAKE': 10,
        'DAY FIREWORKS SHELL': 11,
        'DISPLAY SHELL': 12,
        'LAIN LAIN': 13,
    }

    for name, sort_order in sort_order_map.items():
        Category.objects.filter(name=name).update(sort_order=sort_order)


def unset_category_sort_order(apps, schema_editor):
    Category = apps.get_model('inventory', 'Category')
    Category.objects.all().update(sort_order=99)


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_remove_stockadjustment_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sort_order', 'name']},
        ),
        migrations.AddField(
            model_name='category',
            name='sort_order',
            field=models.PositiveIntegerField(db_index=True, default=99),
        ),
        migrations.RunPython(set_category_sort_order, unset_category_sort_order),
    ]
