# Generated by Django 5.1.7 on 2026-06-18 07:46

import re

from django.db import migrations, models
from django.utils import timezone


def _last_three_digits(value):
    match = re.search(r'(\d{3})$', value)
    if match:
        return int(match.group(1))
    return 0


def _spg_import_sequence(value):
    match = re.search(r'-(\d{3})/KA$', value)
    if match:
        return int(match.group(1))
    return 0


def _seed_sequence(DocumentSequence, family, period_key, current_value):
    sequence, created = DocumentSequence.objects.get_or_create(
        family=family,
        period_key=period_key,
        defaults={'current_value': current_value},
    )
    if not created and sequence.current_value < current_value:
        sequence.current_value = current_value
        sequence.save(update_fields=['current_value', 'updated_at'])


def seed_document_sequences(apps, schema_editor):
    now = timezone.now()
    year = now.year
    month_key = now.strftime('%Y-%m')

    DocumentSequence = apps.get_model('inventory', 'DocumentSequence')
    SPG = apps.get_model('inventory', 'SPG')
    SPK = apps.get_model('inventory', 'SPK')
    SJ = apps.get_model('inventory', 'SJ')
    SuratLain = apps.get_model('inventory', 'SuratLain')
    SuratTransferStok = apps.get_model('inventory', 'SuratTransferStok')
    StockAdjustment = apps.get_model('inventory', 'StockAdjustment')

    spg_import_max = 0
    for value in SPG.objects.filter(document_type='IMPORT', created_at__year=year).values_list('document_number', flat=True):
        sequence = _spg_import_sequence(value)
        if sequence > spg_import_max:
            spg_import_max = sequence
    _seed_sequence(DocumentSequence, 'SPG:IMPORT', str(year), spg_import_max)

    for doc_type in ['BAWANG', 'KAWAT', 'LAIN-LAIN']:
        sequence_max = 0
        for value in SPG.objects.filter(
            document_type=doc_type,
            created_at__year=year,
            created_at__month=now.month,
        ).values_list('document_number', flat=True):
            sequence = _last_three_digits(value)
            if sequence > sequence_max:
                sequence_max = sequence
        _seed_sequence(DocumentSequence, f'SPG:{doc_type}', month_key, sequence_max)

    spk_max = 0
    for value in SPK.objects.filter(created_at__year=year, created_at__month=now.month).values_list('document_number', flat=True):
        sequence = _last_three_digits(value)
        if sequence > spk_max:
            spk_max = sequence
    _seed_sequence(DocumentSequence, 'SPK', month_key, spk_max)

    sj_max = 0
    for value in SJ.objects.filter(created_at__year=year).values_list('sequence_number', flat=True):
        sequence = value or 0
        if sequence > sj_max:
            sj_max = sequence
    _seed_sequence(DocumentSequence, 'SJ', str(year), sj_max)

    for doc_type in ['STB', 'SPB', 'RETUR_PEMBELIAN', 'RETUR_PENJUALAN']:
        sequence_max = 0
        for value in SuratLain.objects.filter(
            document_type=doc_type,
            created_at__year=year,
            created_at__month=now.month,
        ).values_list('document_number', flat=True):
            sequence = _last_three_digits(value)
            if sequence > sequence_max:
                sequence_max = sequence
        _seed_sequence(DocumentSequence, f'SURAT_LAIN:{doc_type}', month_key, sequence_max)

    transfer_max = 0
    for value in SuratTransferStok.objects.filter(created_at__year=year, created_at__month=now.month).values_list('document_number', flat=True):
        sequence = _last_three_digits(value)
        if sequence > transfer_max:
            transfer_max = sequence
    _seed_sequence(DocumentSequence, 'SURAT_TRANSFER_STOK', month_key, transfer_max)

    adjustment_max = 0
    for value in StockAdjustment.objects.filter(created_at__year=year, created_at__month=now.month).values_list('document_number', flat=True):
        sequence = _last_three_digits(value)
        if sequence > adjustment_max:
            adjustment_max = sequence
    _seed_sequence(DocumentSequence, 'STOCK_ADJUSTMENT', month_key, adjustment_max)


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_alter_category_options_category_sort_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.CharField(max_length=50)),
                ('period_key', models.CharField(max_length=20)),
                ('current_value', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('family', 'period_key'), name='unique_document_sequence_family_period')],
            },
        ),
        migrations.RunPython(seed_document_sequences, migrations.RunPython.noop),
    ]
